# Generated by Django 5.2.6 on 2025-09-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_user',
            new_name='user',
        ),
    ]
