# Generated by Django 5.2.6 on 2025-09-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_alter_shippingaddress_shipping_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "در انتظار پرداخت"),
                    ("Processing", "در حال پردازش"),
                    ("Shipped", "ارسال شده به پست"),
                    ("Delivered", "تحویل به مشتری"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
