# Generated by Django 5.2.6 on 2025-09-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
