# Generated by Django 5.2.6 on 2025-10-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_last_update_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت'), ('Processing', 'در حال آماده سازی'), ('Shipped', 'ارسال شده توسط پیک'), ('Delivered', 'تحویل داده شد ')], default='Pending', max_length=50),
        ),
    ]
