# Generated by Django 5.2.6 on 2025-09-06 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_product_is_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="star",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
